### PR TITLE
Run all tests on CI

### PR DESCRIPTION
**Pull request by ddeboer**

### CODE REVIEW

**Comment by ddeboer** [comment]
We now run all tests on CI, including the new ones for the REST API. Unfortunately #394 was merged before the tests were fixed, so we now have a build failure.

@rmies Can you fix those tests?

**Comment by ddeboer** [comment]
@rl-king There you go, failing tests: https://travis-ci.org/driebit/ginger/builds/457959786?utm_source=github_status&utm_medium=notification 😄

**Comment by rl-king** [comment]
Failing rest api tests are fixed. 

Not sure what's the cause of this message though
```
16:13:30.671 [warning] Failed to get page url path. Is the 'page' dispatch rule missing?
undefined
*** test module not found ***
**ok```
https://travis-ci.org/driebit/ginger/builds/459819931#L970

**Comment by rmies** [comment]
I still have failing tests locally which seems to be the result of the default language for the `testsanboxdb` site being `nl` (and not `en`) . Currently looking in to it.

**Comment by rmies** [comment]
My problems were caused by stray `.beam` files.

**Pull request merged**
