### PR TITLE
[remark] Don't link to the anonymous user

### PR DESCRIPTION
**Pull request by fredpook**
@DorienD can you check if I did it right?

### CODE REVIEW

**Comment by DorienD** [comment]
Hmmm, i want to discuss this next week.

**Comment by ddeboer** [comment]
@DorienD @fredpook Has this been discussed?

**Comment by DorienD** [comment]
Yes helemaal goed!

**Comment by Dirklectisch** [comment]
@DorienD Did you guys end up using an anonymous user after all?

**Pull request merged**
