### PR TITLE
removed es6 functionality (ipad3 crashes)

### PR DESCRIPTION
**Pull request by yorivanloo**

### CODE REVIEW

**Comment by ddeboer** [comment]
Can’t we use Babel, so we can move forward and start using ES6 syntax?

**Comment by Devenwel** [comment]
sure, I have a Gulp task in entoen.nu that does this if you need an example

**Comment by Devenwel** [comment]
Also the fat arrows change the way 'this' is bound so be careful in any case rewriting that stuff

**Comment by ddeboer** [comment]
So @Devenwel, since we decided not to use ES6 syntax for now, should we merge this?

**Pull request merged**
