### PR TITLE
make menu dropdowns work on tablets Fix #123

### LINKED ISSUE #65: Dropdown-menu does't close on touchscreen
If you click a menu-item a dropdown opens. On Touchscreen, Ipad for example, you can't close it. 
- I you click the item again you go to the page
- If you scroll down it stays open (over our text and images)

For example: https://geheugenvanoost.ginger-acceptatie.driebit.net
Click on 'laatste toevoegingen'.

This only happens on screens wide enough for the whole menu to show (so they don't have a hamburger menu), such as the Ipad on the horizontal view.

### LINKED ISSUE #123: Hamburger menu UX
Mobile devices: hamburger icon changes into a cross after opening the hamburger menu. To close the menu you can click the cross. The cross then changes back into a hamburger icon.

### PR DESCRIPTION
**Pull request by gunnar-driebit**
Fix #65

### CODE REVIEW

**Comment by ddeboer** [comment]
@DorienD @Devenwel Please review.

**Comment by ddeboer** [comment]
@gunnar-driebit Please add `Fix #123` (number of issue that you’re fixing here) in the PR description, so the issue gets closed automatically.

**Comment by gunnar-driebit** [comment]
Updated after consulting the ux team about the ideal functionality

**Comment by DorienD** [comment]
@gunnar-driebit The first time you touch the submenu on Ipad it disappears when i click outside the submenu. But if i go over another item it doesn't disappear anymore.

**Pull request merged**
