### PR TITLE
170 pdf preview to fit in page

### PR DESCRIPTION
**Pull request by gunnar-driebit**
Fixed the problem with pdf preview being a fixed width, causing it to overflow its boundaries.

### CODE REVIEW

**Comment by ddeboer** [comment]
Please add a reference, like this: `Fix #170`.

**Comment by gunnar-driebit** [comment]
Fix #170

**Comment by ddeboer** [comment]
@Devenwel Do you agree with this fix? It applies to your code.

**Comment by Devenwel** [comment]
Can't remember why I made it 800 px wide, but if the issue is fixed, fine with me.

**Pull request merged**
