### PR TITLE
Summary

### LINKED ISSUE #223: Use summary filter where appropriate
For instance, replace [this](https://github.com/driebit/ginger/blob/master/modules/mod_ginger_base/templates/list/list-item-vertical.tpl#L59-L63) with: `id|summary:70`.

### PR DESCRIPTION
**Pull request by DorienD**
#223, ive changed it for the list items, couldn't find it elsewhere. @ddeboer @fredpook do you know where its also used? Fix #223

### CODE REVIEW

**Comment by ddeboer** [comment]
If you do a search for `id.summary`, you’ll find some more places, but they don’t always have the same logic.

**Comment by ddeboer** [comment]
Please add `Fix #223` to the PR description, so the issue will be automatically closed when we merge this.

**Comment by DorienD** [comment]
Yes indeed, i'm also not sure if we can just add it everywhere. @fredpook could you also take a look at this?

**Comment by ddeboer** [comment]
Not in the title, but in the description. :)

**Pull request merged**
