### PR TITLE
191 masthead image without cropping

### LINKED ISSUE #191: High resolution masthead banner should not be cropped
High resolution banners seem to be cropped by default, and because of the cropping, the image does not show in high res anymore. 
Found out about this at tudelft.openresearch.net and reproduced here: https://mijnzuiderzee.ginger-acceptatie.driebit.net/page/6579/test-zoekopdracht (the image I uploaded is 2900 x 700 px).

### PR DESCRIPTION
**Pull request by gunnar-driebit**
Fix #191

- [x] Dorien removes inline styling
- [x] Dorien checks mediaclass config if only {quality, 85%} is enough

### CODE REVIEW

**Comment by fredpook** [comment]
I think the mediaclass should stay since we want to downscale very large images and upscale low res images. Can you test with adjusting mediaclass.config ?

**Comment by gunnar-driebit** [comment]
I changed the mediaclass.config file in mod_ginger_foundation to optimize the quality vs file size.

**Comment by ddeboer** [comment]
@fredpook Can you test this branch and see how the masthead images turn out?

**Comment by ddeboer** [comment]
Ping @fredpook.

**Comment by DorienD** [comment]
@fredpook allright, i've removed all the inline styling that was not necessary and updated the mediaclass config so it doesn't crop the images. Can you merge this?

**Pull request merged**
