### PR TITLE
[base] Patch resource via REST api

### PR DESCRIPTION
**Pull request by rl-king**
Since there is no PATCH method we use post.

Posting at `/data/resources/id` will update the resource at `id`

### CODE REVIEW

**Comment by ddeboer** [comment]
Actually, updating a single REST resource shouldn’t be PATCH but PUT. Does PUT work?

**Comment by rl-king** [comment]
It it supported, what's implemented here updates the resource, not replace it

**Comment by ddeboer** [comment]
Of course, you’re right! `m_rsc:update/3` indeed _partially_ updates a resource. Still, I’d argue that PUT is semantically closer here than POST, which is about adding new resources.

**Comment by rl-king** [comment]
K I'll update it

**Pull request merged**
