### PR TITLE
Map Query

### LINKED ISSUE #21: Special search query category template for maps searches
In gitlab by dorien on Nov 20, 2015, 16:49

A search-query-map.tpl or something so the editors can make a search query and put the results on a map.

### PR DESCRIPTION
**Pull request by DorienD**
Added a category for showing results of search queries on a map. Fix #21

### CODE REVIEW

**Comment by ddeboer** [comment]
Let’s also add that category to the schema. I’d call it `location_query`.

**Comment by DorienD** [comment]
Check, will do

**Comment by DorienD** [comment]
Done.

**Comment by DorienD** [comment]
This is related to #21

**Comment by ddeboer** [comment]
@DorienD Please add `Fix #21` to the PR description instead of manually closing the issue.

**Comment by DorienD** [comment]
@fredpook wil jij deze mergen?

**Pull request merged**
